// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WmpMessage.proto

package com.keepthinker.wavemessaging.proto;

public final class WmpMessageProtos {
  private WmpMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code tutorial.WmpConnectReturnCode}
   */
  public enum WmpConnectReturnCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ACCEPTED = 0;</code>
     */
    ACCEPTED(0),
    /**
     * <code>REFUSED_UNACCEPTABLE_PROTOCOL_VERSION = 1;</code>
     */
    REFUSED_UNACCEPTABLE_PROTOCOL_VERSION(1),
    /**
     * <code>REFUSED_IDENTIFIER_REJECTED = 2;</code>
     */
    REFUSED_IDENTIFIER_REJECTED(2),
    /**
     * <pre>
     ** not login or error token 
     * </pre>
     *
     * <code>REFUSED_NOT_AUTHORIZED = 3;</code>
     */
    REFUSED_NOT_AUTHORIZED(3),
    /**
     * <pre>
     ** server is busy or not able to provide service
     * </pre>
     *
     * <code>REFUSED_SERVER_UNAVAILABLE = 4;</code>
     */
    REFUSED_SERVER_UNAVAILABLE(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ACCEPTED = 0;</code>
     */
    public static final int ACCEPTED_VALUE = 0;
    /**
     * <code>REFUSED_UNACCEPTABLE_PROTOCOL_VERSION = 1;</code>
     */
    public static final int REFUSED_UNACCEPTABLE_PROTOCOL_VERSION_VALUE = 1;
    /**
     * <code>REFUSED_IDENTIFIER_REJECTED = 2;</code>
     */
    public static final int REFUSED_IDENTIFIER_REJECTED_VALUE = 2;
    /**
     * <pre>
     ** not login or error token 
     * </pre>
     *
     * <code>REFUSED_NOT_AUTHORIZED = 3;</code>
     */
    public static final int REFUSED_NOT_AUTHORIZED_VALUE = 3;
    /**
     * <pre>
     ** server is busy or not able to provide service
     * </pre>
     *
     * <code>REFUSED_SERVER_UNAVAILABLE = 4;</code>
     */
    public static final int REFUSED_SERVER_UNAVAILABLE_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static WmpConnectReturnCode valueOf(int value) {
      return forNumber(value);
    }

    public static WmpConnectReturnCode forNumber(int value) {
      switch (value) {
        case 0: return ACCEPTED;
        case 1: return REFUSED_UNACCEPTABLE_PROTOCOL_VERSION;
        case 2: return REFUSED_IDENTIFIER_REJECTED;
        case 3: return REFUSED_NOT_AUTHORIZED;
        case 4: return REFUSED_SERVER_UNAVAILABLE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<WmpConnectReturnCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        WmpConnectReturnCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<WmpConnectReturnCode>() {
            public WmpConnectReturnCode findValueByNumber(int number) {
              return WmpConnectReturnCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.keepthinker.wavemessaging.proto.WmpMessageProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final WmpConnectReturnCode[] VALUES = values();

    public static WmpConnectReturnCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private WmpConnectReturnCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:tutorial.WmpConnectReturnCode)
  }

  public interface WmpConnectMessageBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.WmpConnectMessageBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string clientId = 1;</code>
     */
    java.lang.String getClientId();
    /**
     * <code>optional string clientId = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>optional string token = 2;</code>
     */
    java.lang.String getToken();
    /**
     * <code>optional string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code tutorial.WmpConnectMessageBody}
   */
  public  static final class WmpConnectMessageBody extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.WmpConnectMessageBody)
      WmpConnectMessageBodyOrBuilder {
    // Use WmpConnectMessageBody.newBuilder() to construct.
    private WmpConnectMessageBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WmpConnectMessageBody() {
      clientId_ = "";
      token_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private WmpConnectMessageBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnectMessageBody_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnectMessageBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody.class, com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody.Builder.class);
    }

    public static final int CLIENTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object clientId_;
    /**
     * <code>optional string clientId = 1;</code>
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string clientId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <code>optional string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>optional string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody)) {
        return super.equals(obj);
      }
      com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody other = (com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody) obj;

      boolean result = true;
      result = result && getClientId()
          .equals(other.getClientId());
      result = result && getToken()
          .equals(other.getToken());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.WmpConnectMessageBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.WmpConnectMessageBody)
        com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnectMessageBody_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnectMessageBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody.class, com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody.Builder.class);
      }

      // Construct using com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientId_ = "";

        token_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnectMessageBody_descriptor;
      }

      public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody getDefaultInstanceForType() {
        return com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody.getDefaultInstance();
      }

      public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody build() {
        com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody buildPartial() {
        com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody result = new com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody(this);
        result.clientId_ = clientId_;
        result.token_ = token_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody) {
          return mergeFrom((com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody other) {
        if (other == com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody.getDefaultInstance()) return this;
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object clientId_ = "";
      /**
       * <code>optional string clientId = 1;</code>
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientId = 1;</code>
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientId = 1;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientId = 1;</code>
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>optional string token = 2;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tutorial.WmpConnectMessageBody)
    }

    // @@protoc_insertion_point(class_scope:tutorial.WmpConnectMessageBody)
    private static final com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody();
    }

    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WmpConnectMessageBody>
        PARSER = new com.google.protobuf.AbstractParser<WmpConnectMessageBody>() {
      public WmpConnectMessageBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new WmpConnectMessageBody(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WmpConnectMessageBody> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WmpConnectMessageBody> getParserForType() {
      return PARSER;
    }

    public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WmpConnAckMessageBodyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.WmpConnAckMessageBody)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string clientId = 1;</code>
     */
    java.lang.String getClientId();
    /**
     * <code>optional string clientId = 1;</code>
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>optional .tutorial.WmpConnectReturnCode returnCode = 3;</code>
     */
    int getReturnCodeValue();
    /**
     * <code>optional .tutorial.WmpConnectReturnCode returnCode = 3;</code>
     */
    com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectReturnCode getReturnCode();
  }
  /**
   * Protobuf type {@code tutorial.WmpConnAckMessageBody}
   */
  public  static final class WmpConnAckMessageBody extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.WmpConnAckMessageBody)
      WmpConnAckMessageBodyOrBuilder {
    // Use WmpConnAckMessageBody.newBuilder() to construct.
    private WmpConnAckMessageBody(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WmpConnAckMessageBody() {
      clientId_ = "";
      returnCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private WmpConnAckMessageBody(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              returnCode_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnAckMessageBody_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnAckMessageBody_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody.class, com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody.Builder.class);
    }

    public static final int CLIENTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object clientId_;
    /**
     * <code>optional string clientId = 1;</code>
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string clientId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RETURNCODE_FIELD_NUMBER = 3;
    private int returnCode_;
    /**
     * <code>optional .tutorial.WmpConnectReturnCode returnCode = 3;</code>
     */
    public int getReturnCodeValue() {
      return returnCode_;
    }
    /**
     * <code>optional .tutorial.WmpConnectReturnCode returnCode = 3;</code>
     */
    public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectReturnCode getReturnCode() {
      com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectReturnCode result = com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectReturnCode.valueOf(returnCode_);
      return result == null ? com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectReturnCode.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
      }
      if (returnCode_ != com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectReturnCode.ACCEPTED.getNumber()) {
        output.writeEnum(3, returnCode_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
      }
      if (returnCode_ != com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectReturnCode.ACCEPTED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, returnCode_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody)) {
        return super.equals(obj);
      }
      com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody other = (com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody) obj;

      boolean result = true;
      result = result && getClientId()
          .equals(other.getClientId());
      result = result && returnCode_ == other.returnCode_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + RETURNCODE_FIELD_NUMBER;
      hash = (53 * hash) + returnCode_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.WmpConnAckMessageBody}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.WmpConnAckMessageBody)
        com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBodyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnAckMessageBody_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnAckMessageBody_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody.class, com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody.Builder.class);
      }

      // Construct using com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientId_ = "";

        returnCode_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnAckMessageBody_descriptor;
      }

      public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody getDefaultInstanceForType() {
        return com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody.getDefaultInstance();
      }

      public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody build() {
        com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody buildPartial() {
        com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody result = new com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody(this);
        result.clientId_ = clientId_;
        result.returnCode_ = returnCode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody) {
          return mergeFrom((com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody other) {
        if (other == com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody.getDefaultInstance()) return this;
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (other.returnCode_ != 0) {
          setReturnCodeValue(other.getReturnCodeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object clientId_ = "";
      /**
       * <code>optional string clientId = 1;</code>
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientId = 1;</code>
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientId = 1;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientId = 1;</code>
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private int returnCode_ = 0;
      /**
       * <code>optional .tutorial.WmpConnectReturnCode returnCode = 3;</code>
       */
      public int getReturnCodeValue() {
        return returnCode_;
      }
      /**
       * <code>optional .tutorial.WmpConnectReturnCode returnCode = 3;</code>
       */
      public Builder setReturnCodeValue(int value) {
        returnCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .tutorial.WmpConnectReturnCode returnCode = 3;</code>
       */
      public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectReturnCode getReturnCode() {
        com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectReturnCode result = com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectReturnCode.valueOf(returnCode_);
        return result == null ? com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectReturnCode.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .tutorial.WmpConnectReturnCode returnCode = 3;</code>
       */
      public Builder setReturnCode(com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectReturnCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        returnCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .tutorial.WmpConnectReturnCode returnCode = 3;</code>
       */
      public Builder clearReturnCode() {
        
        returnCode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tutorial.WmpConnAckMessageBody)
    }

    // @@protoc_insertion_point(class_scope:tutorial.WmpConnAckMessageBody)
    private static final com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody();
    }

    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WmpConnAckMessageBody>
        PARSER = new com.google.protobuf.AbstractParser<WmpConnAckMessageBody>() {
      public WmpConnAckMessageBody parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new WmpConnAckMessageBody(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WmpConnAckMessageBody> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WmpConnAckMessageBody> getParserForType() {
      return PARSER;
    }

    public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnAckMessageBody getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_WmpConnectMessageBody_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_WmpConnectMessageBody_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_WmpConnAckMessageBody_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_WmpConnAckMessageBody_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020WmpMessage.proto\022\010tutorial\"8\n\025WmpConne" +
      "ctMessageBody\022\020\n\010clientId\030\001 \001(\t\022\r\n\005token" +
      "\030\002 \001(\t\"]\n\025WmpConnAckMessageBody\022\020\n\010clien" +
      "tId\030\001 \001(\t\0222\n\nreturnCode\030\003 \001(\0162\036.tutorial" +
      ".WmpConnectReturnCode*\254\001\n\024WmpConnectRetu" +
      "rnCode\022\014\n\010ACCEPTED\020\000\022)\n%REFUSED_UNACCEPT" +
      "ABLE_PROTOCOL_VERSION\020\001\022\037\n\033REFUSED_IDENT" +
      "IFIER_REJECTED\020\002\022\032\n\026REFUSED_NOT_AUTHORIZ" +
      "ED\020\003\022\036\n\032REFUSED_SERVER_UNAVAILABLE\020\004B7\n#" +
      "com.keepthinker.wavemessaging.protoB\020Wmp",
      "MessageProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_WmpConnectMessageBody_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_WmpConnectMessageBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_WmpConnectMessageBody_descriptor,
        new java.lang.String[] { "ClientId", "Token", });
    internal_static_tutorial_WmpConnAckMessageBody_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_WmpConnAckMessageBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_WmpConnAckMessageBody_descriptor,
        new java.lang.String[] { "ClientId", "ReturnCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
