// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WmpMessage.proto

package com.keepthinker.wavemessaging.proto;

public final class WmpMessageProtos {
  private WmpMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WmpConnectMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.WmpConnectMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 clientId = 1;</code>
     */
    long getClientId();

    /**
     * <code>optional string token = 2;</code>
     */
    java.lang.String getToken();
    /**
     * <code>optional string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code tutorial.WmpConnectMessage}
   */
  public  static final class WmpConnectMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.WmpConnectMessage)
      WmpConnectMessageOrBuilder {
    // Use WmpConnectMessage.newBuilder() to construct.
    private WmpConnectMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WmpConnectMessage() {
      clientId_ = 0L;
      token_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private WmpConnectMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              clientId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnectMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnectMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage.class, com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage.Builder.class);
    }

    public static final int CLIENTID_FIELD_NUMBER = 1;
    private long clientId_;
    /**
     * <code>optional int64 clientId = 1;</code>
     */
    public long getClientId() {
      return clientId_;
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object token_;
    /**
     * <code>optional string token = 2;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>optional string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (clientId_ != 0L) {
        output.writeInt64(1, clientId_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (clientId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, clientId_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage)) {
        return super.equals(obj);
      }
      com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage other = (com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage) obj;

      boolean result = true;
      result = result && (getClientId()
          == other.getClientId());
      result = result && getToken()
          .equals(other.getToken());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getClientId());
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.WmpConnectMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.WmpConnectMessage)
        com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnectMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnectMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage.class, com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage.Builder.class);
      }

      // Construct using com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientId_ = 0L;

        token_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnectMessage_descriptor;
      }

      public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage getDefaultInstanceForType() {
        return com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage.getDefaultInstance();
      }

      public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage build() {
        com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage buildPartial() {
        com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage result = new com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage(this);
        result.clientId_ = clientId_;
        result.token_ = token_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage) {
          return mergeFrom((com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage other) {
        if (other == com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage.getDefaultInstance()) return this;
        if (other.getClientId() != 0L) {
          setClientId(other.getClientId());
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long clientId_ ;
      /**
       * <code>optional int64 clientId = 1;</code>
       */
      public long getClientId() {
        return clientId_;
      }
      /**
       * <code>optional int64 clientId = 1;</code>
       */
      public Builder setClientId(long value) {
        
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 clientId = 1;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>optional string token = 2;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tutorial.WmpConnectMessage)
    }

    // @@protoc_insertion_point(class_scope:tutorial.WmpConnectMessage)
    private static final com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage();
    }

    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WmpConnectMessage>
        PARSER = new com.google.protobuf.AbstractParser<WmpConnectMessage>() {
      public WmpConnectMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new WmpConnectMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WmpConnectMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WmpConnectMessage> getParserForType() {
      return PARSER;
    }

    public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnectMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WmpConnackMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.WmpConnackMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 clientId = 1;</code>
     */
    long getClientId();

    /**
     * <code>optional int32 returnCode = 2;</code>
     */
    int getReturnCode();
  }
  /**
   * Protobuf type {@code tutorial.WmpConnackMessage}
   */
  public  static final class WmpConnackMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.WmpConnackMessage)
      WmpConnackMessageOrBuilder {
    // Use WmpConnackMessage.newBuilder() to construct.
    private WmpConnackMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WmpConnackMessage() {
      clientId_ = 0L;
      returnCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private WmpConnackMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              clientId_ = input.readInt64();
              break;
            }
            case 16: {

              returnCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnackMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnackMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage.class, com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage.Builder.class);
    }

    public static final int CLIENTID_FIELD_NUMBER = 1;
    private long clientId_;
    /**
     * <code>optional int64 clientId = 1;</code>
     */
    public long getClientId() {
      return clientId_;
    }

    public static final int RETURNCODE_FIELD_NUMBER = 2;
    private int returnCode_;
    /**
     * <code>optional int32 returnCode = 2;</code>
     */
    public int getReturnCode() {
      return returnCode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (clientId_ != 0L) {
        output.writeInt64(1, clientId_);
      }
      if (returnCode_ != 0) {
        output.writeInt32(2, returnCode_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (clientId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, clientId_);
      }
      if (returnCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, returnCode_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage)) {
        return super.equals(obj);
      }
      com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage other = (com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage) obj;

      boolean result = true;
      result = result && (getClientId()
          == other.getClientId());
      result = result && (getReturnCode()
          == other.getReturnCode());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getClientId());
      hash = (37 * hash) + RETURNCODE_FIELD_NUMBER;
      hash = (53 * hash) + getReturnCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.WmpConnackMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.WmpConnackMessage)
        com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnackMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnackMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage.class, com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage.Builder.class);
      }

      // Construct using com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        clientId_ = 0L;

        returnCode_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.keepthinker.wavemessaging.proto.WmpMessageProtos.internal_static_tutorial_WmpConnackMessage_descriptor;
      }

      public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage getDefaultInstanceForType() {
        return com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage.getDefaultInstance();
      }

      public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage build() {
        com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage buildPartial() {
        com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage result = new com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage(this);
        result.clientId_ = clientId_;
        result.returnCode_ = returnCode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage) {
          return mergeFrom((com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage other) {
        if (other == com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage.getDefaultInstance()) return this;
        if (other.getClientId() != 0L) {
          setClientId(other.getClientId());
        }
        if (other.getReturnCode() != 0) {
          setReturnCode(other.getReturnCode());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long clientId_ ;
      /**
       * <code>optional int64 clientId = 1;</code>
       */
      public long getClientId() {
        return clientId_;
      }
      /**
       * <code>optional int64 clientId = 1;</code>
       */
      public Builder setClientId(long value) {
        
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 clientId = 1;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = 0L;
        onChanged();
        return this;
      }

      private int returnCode_ ;
      /**
       * <code>optional int32 returnCode = 2;</code>
       */
      public int getReturnCode() {
        return returnCode_;
      }
      /**
       * <code>optional int32 returnCode = 2;</code>
       */
      public Builder setReturnCode(int value) {
        
        returnCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 returnCode = 2;</code>
       */
      public Builder clearReturnCode() {
        
        returnCode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tutorial.WmpConnackMessage)
    }

    // @@protoc_insertion_point(class_scope:tutorial.WmpConnackMessage)
    private static final com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage();
    }

    public static com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WmpConnackMessage>
        PARSER = new com.google.protobuf.AbstractParser<WmpConnackMessage>() {
      public WmpConnackMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new WmpConnackMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WmpConnackMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WmpConnackMessage> getParserForType() {
      return PARSER;
    }

    public com.keepthinker.wavemessaging.proto.WmpMessageProtos.WmpConnackMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_WmpConnectMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_WmpConnectMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_WmpConnackMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tutorial_WmpConnackMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020WmpMessage.proto\022\010tutorial\"4\n\021WmpConne" +
      "ctMessage\022\020\n\010clientId\030\001 \001(\003\022\r\n\005token\030\002 \001" +
      "(\t\"9\n\021WmpConnackMessage\022\020\n\010clientId\030\001 \001(" +
      "\003\022\022\n\nreturnCode\030\002 \001(\005B7\n#com.keepthinker" +
      ".wavemessaging.protoB\020WmpMessageProtosb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tutorial_WmpConnectMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tutorial_WmpConnectMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_WmpConnectMessage_descriptor,
        new java.lang.String[] { "ClientId", "Token", });
    internal_static_tutorial_WmpConnackMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tutorial_WmpConnackMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tutorial_WmpConnackMessage_descriptor,
        new java.lang.String[] { "ClientId", "ReturnCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
